services:
  database:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "test"
  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    environment:
      DB_HOST: "database"
      DB_NAME: "test"
      REDIS_URL: redis://redis:6379/0
    command: ruby app.rb
  redis:
    image: redis:6.2.11-alpine
